#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ime,            sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           testime,       tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LiftLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	//	bStopTasksBetweenMor	des = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	wait1Msec(2000);

	while(nMotorEncoder[testime] > -2200)
	{
		//Move forward at half power
	motor[testime] = 127;

 }

	motor[testime] = 0;

}
/*
bool moving = true;
while (moving)
{
motor(FrontLeft)=127;
motor(FrontRight)= 127;
motor(BackLeft) = 127;
motor(BackRight) = 127;

wait1Msec(1000);

motor(FrontLeft)=0;
motor(FrontRight)= 0;
motor(BackLeft) = 0;
motor(BackRight) = 0;

wait1Msec(500);

moving = false;

}
moving = true;

// rotate left for 1 second
while (moving)
{
motor(FrontLeft)=-127;
motor(FrontRight)= 127;
motor(BackLeft) = -127;
motor(BackRight) = 127;

wait1Msec(5000);

motor(FrontLeft)=0;
motor(FrontRight)= 0;
motor(BackLeft) = 0;
motor(BackRight) = 0;
moving = false;
}
*/



/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		wait1Msec(20);

		//Driving Motor Control with Remote Control 1
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[FrontLeft] = vexRT[Ch3] / 2;
		motor[BackLeft] = vexRT[Ch3] / 2;
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[FrontRight] = vexRT[Ch2] / 2;
		motor[BackRight] = vexRT[Ch2] / 2;

		while(vexRT(Btn5U) == 1)
		{
			motor(Claw) = 127;
		}
		while (vexRT(Btn5D) == 1)
		{
			motor(Claw)= -127;
		}
		motor(Claw) = 0;

		while(vexRT(Btn6U))
		{
			motor(LiftLeft) = 127;
			motor(LiftRight) =127;
		}
		motor(LiftLeft) = 25;
		motor(LiftRight) = 25;

		while(vexRT(Btn6D))
		{
			motor(LiftLeft) = -127;
			motor(LiftRight) = -127;
		}
		motor(LiftLeft) = 25;
		motor(LiftRight) = 25;
	}

}
